source: docs
api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
mapboxjs: v2.0.0
mapboxjsbase: https://api.tiles.mapbox.com/mapbox.js/v2.0.0-beta1
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
exclude: [dist]
